export type Category =
  | "grooming-salon"
  | "mobile-grooming"
  | "self-service-bath"
  | "vet-grooming";

export type Business = {
  id: string;
  slug: string;
  name: string;
  category: Category;
  city: string;
  state: string;
  address: string;
  phone: string;
  website?: string;
  rating: number;
  reviewCount: number;
  description: string;
  services: string[];
  hours: Record<string, string>;
  badge?: string;
  featured?: boolean;
  image: string;
};

export const CATEGORIES: { value: Category | "all"; label: string }[] = [
  { value: "all", label: "All" },
  { value: "grooming-salon", label: "Grooming Salon" },
  { value: "mobile-grooming", label: "Mobile Grooming" },
  { value: "self-service-bath", label: "Self-Service Bath" },
  { value: "vet-grooming", label: "Vet Grooming" },
];

export const businesses: Business[] = [
  {
    id: "1",
    slug: "pawfect-cuts-austin",
    name: "Pawfect Cuts",
    category: "grooming-salon",
    city: "Austin",
    state: "TX",
    address: "1204 S Congress Ave, Austin, TX 78704",
    phone: "(512) 555-0192",
    website: "https://pawfectcuts.example.com",
    rating: 4.9,
    reviewCount: 312,
    description:
      "Austin's most-loved grooming salon, specializing in breed-specific cuts and color-safe shampoos. Our certified groomers treat every dog like family.",
    services: ["Full Groom", "Bath & Brush", "Haircut", "Nail Trim", "Teeth Brushing", "De-shedding Treatment"],
    hours: {
      Monday: "8 AM – 6 PM",
      Tuesday: "8 AM – 6 PM",
      Wednesday: "8 AM – 6 PM",
      Thursday: "8 AM – 7 PM",
      Friday: "8 AM – 7 PM",
      Saturday: "9 AM – 5 PM",
      Sunday: "Closed",
    },
    badge: "Top Rated",
    featured: true,
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&q=80&auto=format&fit=crop",
  },
  {
    id: "2",
    slug: "sudsy-paws-mobile-dallas",
    name: "Sudsy Paws Mobile",
    category: "mobile-grooming",
    city: "Dallas",
    state: "TX",
    address: "Serving the Dallas metro area",
    phone: "(214) 555-0847",
    rating: 4.8,
    reviewCount: 198,
    description:
      "We come to you! Our fully-equipped van brings spa-quality grooming right to your driveway. No cages, no stress — just a relaxed, one-on-one experience.",
    services: ["Full Groom", "Bath & Dry", "Nail Trim", "Ear Cleaning", "Flea Treatment"],
    hours: {
      Monday: "7 AM – 5 PM",
      Tuesday: "7 AM – 5 PM",
      Wednesday: "7 AM – 5 PM",
      Thursday: "7 AM – 5 PM",
      Friday: "7 AM – 5 PM",
      Saturday: "8 AM – 3 PM",
      Sunday: "Closed",
    },
    badge: "Most Popular",
    featured: true,
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&q=80&auto=format&fit=crop",
  },
  {
    id: "3",
    slug: "splash-station-denver",
    name: "Splash Station",
    category: "self-service-bath",
    city: "Denver",
    state: "CO",
    address: "750 Colfax Ave, Denver, CO 80203",
    phone: "(720) 555-0334",
    rating: 4.6,
    reviewCount: 145,
    description:
      "DIY dog washing made easy. We supply the tubs, towels, shampoos, and dryers — you do the bathing. Perfect for owners who like hands-on care without the mess at home.",
    services: ["Self-Service Bath Station", "Blow Dry Station", "Towel Rental", "Shampoo & Conditioner Provided", "Nail Grinding (add-on)"],
    hours: {
      Monday: "9 AM – 7 PM",
      Tuesday: "9 AM – 7 PM",
      Wednesday: "9 AM – 7 PM",
      Thursday: "9 AM – 7 PM",
      Friday: "9 AM – 7 PM",
      Saturday: "8 AM – 8 PM",
      Sunday: "10 AM – 6 PM",
    },
    image: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=800&q=80&auto=format&fit=crop",
  },
  {
    id: "4",
    slug: "wagging-tails-grooming-chicago",
    name: "Wagging Tails Grooming",
    category: "grooming-salon",
    city: "Chicago",
    state: "IL",
    address: "3311 N Clark St, Chicago, IL 60657",
    phone: "(773) 555-0561",
    website: "https://waggingtails.example.com",
    rating: 4.7,
    reviewCount: 267,
    description:
      "A boutique grooming salon in the heart of Lakeview. We use only organic, hypoallergenic products and offer a calm, low-anxiety environment for anxious dogs.",
    services: ["Full Groom", "Puppy's First Groom", "Organic Spa Bath", "De-shedding", "Flea & Tick Shampoo", "Bandana & Bow"],
    hours: {
      Monday: "9 AM – 5 PM",
      Tuesday: "9 AM – 5 PM",
      Wednesday: "9 AM – 5 PM",
      Thursday: "9 AM – 6 PM",
      Friday: "9 AM – 6 PM",
      Saturday: "9 AM – 4 PM",
      Sunday: "Closed",
    },
    image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&q=80&auto=format&fit=crop",
  },
  {
    id: "5",
    slug: "dr-fluffys-vet-grooming-seattle",
    name: "Dr. Fluffy's Vet Grooming",
    category: "vet-grooming",
    city: "Seattle",
    state: "WA",
    address: "420 Eastlake Ave E, Seattle, WA 98102",
    phone: "(206) 555-0728",
    website: "https://drfluffys.example.com",
    rating: 4.9,
    reviewCount: 89,
    description:
      "Grooming performed under veterinary supervision. Ideal for senior dogs, dogs with health conditions, or highly anxious pets who need extra care and monitoring.",
    services: ["Medical Bath", "Full Groom", "Sedation Grooming (vet-supervised)", "Skin Treatment Bath", "Nail Trim", "Ear Flush"],
    hours: {
      Monday: "8 AM – 5 PM",
      Tuesday: "8 AM – 5 PM",
      Wednesday: "8 AM – 5 PM",
      Thursday: "8 AM – 5 PM",
      Friday: "8 AM – 4 PM",
      Saturday: "9 AM – 2 PM",
      Sunday: "Closed",
    },
    badge: "Vet-Supervised",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&q=80&auto=format&fit=crop",
  },
  {
    id: "6",
    slug: "clean-canine-mobile-miami",
    name: "Clean Canine Mobile",
    category: "mobile-grooming",
    city: "Miami",
    state: "FL",
    address: "Serving Miami-Dade County",
    phone: "(305) 555-0415",
    rating: 4.5,
    reviewCount: 203,
    description:
      "South Florida's top-rated mobile groomer. Our climate-controlled van keeps your pup comfortable even in the Miami heat. Bilingual staff (English & Spanish).",
    services: ["Full Groom", "Bath & Brush Out", "Teeth Brushing", "Ear Cleaning", "Paw Balm Treatment"],
    hours: {
      Monday: "7 AM – 6 PM",
      Tuesday: "7 AM – 6 PM",
      Wednesday: "7 AM – 6 PM",
      Thursday: "7 AM – 6 PM",
      Friday: "7 AM – 6 PM",
      Saturday: "8 AM – 4 PM",
      Sunday: "9 AM – 2 PM",
    },
    image: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&q=80&auto=format&fit=crop",
  },
  {
    id: "7",
    slug: "the-grooming-lounge-nyc",
    name: "The Grooming Lounge",
    category: "grooming-salon",
    city: "New York",
    state: "NY",
    address: "54 W 21st St, New York, NY 10010",
    phone: "(212) 555-0903",
    website: "https://groominglounge.example.com",
    rating: 4.8,
    reviewCount: 521,
    description:
      "Manhattan's premier dog grooming destination. Appointments available same-day. We accommodate all breeds and sizes with individualized care plans.",
    services: ["Full Groom", "Express Bath", "Show Trim", "Blueberry Facial", "Hot Oil Treatment", "Nail Art"],
    hours: {
      Monday: "8 AM – 8 PM",
      Tuesday: "8 AM – 8 PM",
      Wednesday: "8 AM – 8 PM",
      Thursday: "8 AM – 8 PM",
      Friday: "8 AM – 8 PM",
      Saturday: "9 AM – 7 PM",
      Sunday: "10 AM – 5 PM",
    },
    badge: "Open Late",
    image: "https://images.unsplash.com/photo-1534361881754-be0e6e8df6c5?w=800&q=80&auto=format&fit=crop",
  },
  {
    id: "8",
    slug: "pups-n-suds-portland",
    name: "Pups N Suds",
    category: "self-service-bath",
    city: "Portland",
    state: "OR",
    address: "2204 NE Alberta St, Portland, OR 97211",
    phone: "(503) 555-0672",
    rating: 4.4,
    reviewCount: 118,
    description:
      "Portland's cozy self-wash spot. All-natural, locally-sourced shampoos and conditioners. Warm water tubs with adjustable height so your back doesn't ache.",
    services: ["Self-Wash Tub", "Shampoo Bar (15+ scents)", "Force Dryer", "Brush-Out Station", "Bandana (included)"],
    hours: {
      Monday: "10 AM – 6 PM",
      Tuesday: "10 AM – 6 PM",
      Wednesday: "10 AM – 6 PM",
      Thursday: "10 AM – 7 PM",
      Friday: "10 AM – 7 PM",
      Saturday: "9 AM – 7 PM",
      Sunday: "10 AM – 5 PM",
    },
    image: "https://images.unsplash.com/photo-1625794084867-8ddd239946b1?w=800&q=80&auto=format&fit=crop",
  },
  {
    id: "9",
    slug: "four-paws-salon-phoenix",
    name: "Four Paws Salon",
    category: "grooming-salon",
    city: "Phoenix",
    state: "AZ",
    address: "8810 N Central Ave, Phoenix, AZ 85020",
    phone: "(602) 555-0183",
    rating: 4.6,
    reviewCount: 174,
    description:
      "A family-run grooming salon serving Phoenix since 2009. We specialize in double-coated breeds like Huskies, Goldens, and Bernese Mountain Dogs.",
    services: ["Full Groom", "De-shed Blast", "Undercoat Removal", "Blueberry Facial", "Nail Trim & File", "Cologne Spritz"],
    hours: {
      Monday: "8 AM – 5 PM",
      Tuesday: "8 AM – 5 PM",
      Wednesday: "8 AM – 5 PM",
      Thursday: "8 AM – 5 PM",
      Friday: "8 AM – 5 PM",
      Saturday: "9 AM – 3 PM",
      Sunday: "Closed",
    },
    image: "https://images.unsplash.com/photo-1549297689-5f3d34e5d5a1?w=800&q=80&auto=format&fit=crop",
  },
  {
    id: "10",
    slug: "boulevard-bark-mobile-la",
    name: "Boulevard Bark Mobile",
    category: "mobile-grooming",
    city: "Los Angeles",
    state: "CA",
    address: "Serving West LA & Santa Monica",
    phone: "(310) 555-0246",
    website: "https://boulevardbark.example.com",
    rating: 4.7,
    reviewCount: 389,
    description:
      "Celebrity dogs and rescue pups alike get the star treatment. Our mobile unit serves West LA with flexible scheduling and breed-specialist groomers.",
    services: ["Full Groom", "Puppy Package", "Senior Dog Gentle Bath", "Anal Gland Expression", "Ear Cleaning", "Paw Trim"],
    hours: {
      Monday: "7 AM – 7 PM",
      Tuesday: "7 AM – 7 PM",
      Wednesday: "7 AM – 7 PM",
      Thursday: "7 AM – 7 PM",
      Friday: "7 AM – 7 PM",
      Saturday: "8 AM – 5 PM",
      Sunday: "9 AM – 3 PM",
    },
    badge: "Top Rated",
    featured: true,
    image: "https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=800&q=80&auto=format&fit=crop",
  },
  {
    id: "11",
    slug: "healthy-hound-vet-grooming-boston",
    name: "Healthy Hound Vet Grooming",
    category: "vet-grooming",
    city: "Boston",
    state: "MA",
    address: "1 Longfellow Pl, Boston, MA 02114",
    phone: "(617) 555-0537",
    rating: 4.8,
    reviewCount: 62,
    description:
      "Grooming integrated with your dog's wellness visit. Operated inside a full-service animal hospital — perfect for pets with skin conditions, allergies, or post-surgery care.",
    services: ["Medicated Bath", "Full Groom", "Dermatology Shampoo", "Wound-Care Bath", "Nail Trim", "Anal Gland Expression"],
    hours: {
      Monday: "8 AM – 4 PM",
      Tuesday: "8 AM – 4 PM",
      Wednesday: "8 AM – 4 PM",
      Thursday: "8 AM – 4 PM",
      Friday: "8 AM – 4 PM",
      Saturday: "Closed",
      Sunday: "Closed",
    },
    badge: "Vet-Supervised",
    image: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=800&q=80&auto=format&fit=crop",
  },
  {
    id: "12",
    slug: "wag-wash-self-service-nashville",
    name: "Wag & Wash",
    category: "self-service-bath",
    city: "Nashville",
    state: "TN",
    address: "510 Gallatin Ave, Nashville, TN 37206",
    phone: "(615) 555-0791",
    rating: 4.3,
    reviewCount: 96,
    description:
      "East Nashville's chill self-service dog wash. Drop in anytime, no appointment needed. We also sell locally-made dog treats and accessories.",
    services: ["Self-Wash Tubs", "Blow Dry", "Shampoo & Conditioner", "Towels Included", "Treats & Accessories Shop"],
    hours: {
      Monday: "9 AM – 7 PM",
      Tuesday: "9 AM – 7 PM",
      Wednesday: "9 AM – 7 PM",
      Thursday: "9 AM – 7 PM",
      Friday: "9 AM – 8 PM",
      Saturday: "8 AM – 8 PM",
      Sunday: "10 AM – 6 PM",
    },
    image: "https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=800&q=80&auto=format&fit=crop",
  },
  {
    id: "13",
    slug: "snip-snap-grooming-atlanta",
    name: "Snip & Snap Grooming",
    category: "grooming-salon",
    city: "Atlanta",
    state: "GA",
    address: "675 Ponce De Leon Ave NE, Atlanta, GA 30308",
    phone: "(404) 555-0829",
    rating: 4.5,
    reviewCount: 233,
    description:
      "Intown Atlanta's go-to grooming spot. Walk-ins welcome for baths and nail trims. Full grooms by appointment. Instagram-worthy finishes guaranteed.",
    services: ["Full Groom", "Bath Only", "Nail Trim Walk-In", "Puppy Intro Groom", "Shedding Control", "Creative Coloring"],
    hours: {
      Monday: "9 AM – 6 PM",
      Tuesday: "9 AM – 6 PM",
      Wednesday: "9 AM – 6 PM",
      Thursday: "9 AM – 6 PM",
      Friday: "9 AM – 6 PM",
      Saturday: "8 AM – 5 PM",
      Sunday: "11 AM – 4 PM",
    },
    image: "https://images.unsplash.com/photo-1596492784531-6e6eb5ea9993?w=800&q=80&auto=format&fit=crop",
  },
  {
    id: "14",
    slug: "mobile-mutt-makeover-san-francisco",
    name: "Mobile Mutt Makeover",
    category: "mobile-grooming",
    city: "San Francisco",
    state: "CA",
    address: "Serving SF, Oakland & Berkeley",
    phone: "(415) 555-0064",
    website: "https://muttmakeover.example.com",
    rating: 4.6,
    reviewCount: 277,
    description:
      "Bay Area mobile grooming with a green twist — we use biodegradable products and recycle our water. Small-to-medium dogs our specialty.",
    services: ["Full Groom", "Eco Bath", "Nail Trim", "Ear Cleaning", "Flea & Tick Treatment", "Bandana"],
    hours: {
      Monday: "8 AM – 5 PM",
      Tuesday: "8 AM – 5 PM",
      Wednesday: "8 AM – 5 PM",
      Thursday: "8 AM – 5 PM",
      Friday: "8 AM – 5 PM",
      Saturday: "9 AM – 4 PM",
      Sunday: "Closed",
    },
    badge: "Eco-Friendly",
    image: "https://images.unsplash.com/photo-1543466835-00a7240143b1?w=800&q=80&auto=format&fit=crop",
  },
];
